### ISSUE TITLE
Node page should state this package is deprecated

### ISSUE THREAD

**Issue by WalkerCodeRanger** [lydell/autoprefixer-brunch#11]
The [readme](https://github.com/lydell/autoprefixer-brunch/blob/master/readme.md) states "Deprecated. Please use postcss-brunch instead."  However, the [node package page](https://www.npmjs.com/package/autoprefixer-brunch) does not.  It should.

**Comment by lydell** [comment]
Oops, I forgot to release a new version with the deprecation message in it. Should be fixed now. Thanks for reminding me!
